/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Future Cop: L.A.P.D.)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80097208u
#define func_80097208 BootEntry  /* alias */
